---
name: Attestation

on:
  pull_request:

permissions:
  contents: read

jobs:
  container:
    runs-on: ubuntu-latest
    name: Container
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_multistage
          tags: ghcr.io/${{ github.repository }}:sample
          push: true
      - uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
