---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    strategy:
      max-parallel: 4
      matrix:
        java-version: ["22"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew test

  check:
    runs-on: ubuntu-latest
    name: Check Code
    strategy:
      max-parallel: 4
      matrix:
        java-version: ["22"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew check
        continue-on-error: true # Continue even if there are errors

  hadolint:
    runs-on: ubuntu-latest
    name: Lint Dockerfile

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest
    name: Build Jar File
    needs:
      - test
      - check
    strategy:
      max-parallel: 4
      matrix:
        java-version: ["22"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew bootJar
      
      - uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/bswe.jar

  container:
    runs-on: ubuntu-latest
    name: Container
    needs:
      - build
      - hadolint
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/
    
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}:latest
          push: ${{ github.ref == 'refs/heads/main' }}
